[build]
  # Build command for React + Vite
  command = "cd client && npm run build"
  
  # Directory to publish (Vite default output)
  publish = "client/dist"
  
  # Functions directory for serverless functions
  functions = "netlify/functions"

[build.environment]
  # Node version for build
  NODE_VERSION = "18"
  NPM_VERSION = "8"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    
    # Performance headers
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate"

# Redirects for SPA routing
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Edge Functions for enhanced performance
[[edge_functions]]
  function = "auth-middleware"
  path = "/api/auth/*"

# Environment variables hints (actual values set in Netlify dashboard)
# Note: Don't put sensitive values here - set them in Netlify Dashboard
[context.production.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "8"
  VITE_APP_NAME = "OncoVista"
  VITE_ENVIRONMENT = "production"
  # Set these in Netlify Dashboard:
  # VITE_SUPABASE_URL = "your-supabase-url"
  # VITE_SUPABASE_ANON_KEY = "your-anon-key"
  # SUPABASE_SERVICE_KEY = "your-service-key"

# Development server proxy for local testing
[dev]
  command = "cd client && npm run dev"
  port = 5173
  
  [[dev.redirects]]
    from = "/api/*"
    to = "http://localhost:3001/api/:splat"
    status = 200
